import type { Metadata } from 'next';
import { TournamentBoard } from '@/components/demo/TournamentBoard';
import { Tile } from '@/components/Tile';
import type { QueryParams } from '@/lib/demo';
import { parseFlips, parseTournamentConfig } from '@/lib/demo';

export const metadata: Metadata = {
  title: 'Tournament demo — CourtSync',
  description:
    'Run a one-day tournament through the real CourtSync scheduling engine: pool draw, grid, referees, standings and a bracket that recomputes when a score is corrected.',
};

/**
 * The config is parsed on the server and handed down as props rather than
 * read from `window.location` on the client. Reading it in the browser would
 * render defaults on the server and something else on hydration, and the
 * mismatch would show as a flash of the wrong schedule.
 */
export default async function TournamentDemoPage({
  searchParams,
}: {
  searchParams: Promise<QueryParams>;
}) {
  const params = await searchParams;

  return (
    <>
      <Tile surface="canvas" width="wide">
        <h1 className="text-display-md sm:text-display-lg">Tournament demo</h1>
        <p className="mt-4 max-w-2xl text-body text-ink-muted-80">
          A one-day event, pools into a bracket. Everything below is generated by the same functions
          the real app will call — nothing on this page is a mockup, and nothing on it is saved.
        </p>
      </Tile>

      <Tile surface="parchment" width="wide">
        <TournamentBoard
          initialConfig={parseTournamentConfig(params)}
          initialFlips={parseFlips(params)}
        />
      </Tile>
    </>
  );
}
